export interface IEmployee {
    id: number,
    empId: string,
    name :string,
    password: string,
    fatherName: string,
    mobileNo: string,
    email: string,
    department: number,
    address: string,
    dateofBirth: Date,
    dateofJoin: Date,
    dateofReleave: Date,
    experience: string,
    designation: number,
    idProofs: string,
    aboutUs: string,
    isActive: boolean,
    isDeleted:boolean,
    createdDate: Date,
    cretedBy: string,
    modifiedDate: Date,
    modifiedBy: string
    
}